;;;; library(lists) and library(apply) tests: sum_list/max_list/min_list,
;;;; numlist, list_to_set, subtract/intersection/union, permutation, and the
;;;; meta-predicates maplist/foldl/include/exclude/partition.

(in-package #:cl-prolog.tests)

(deftest-queries list-extra-builtins ((make-rulebase))
  ((cl-prolog::sum_list (1 2 3 4) ?s)      :ordered (((?s . 10))))
  ((cl-prolog::sumlist (1 2 3) ?s)         :ordered (((?s . 6))))
  ((cl-prolog::sum_list () ?s)             :ordered (((?s . 0))))
  ((cl-prolog::max_list (3 9 2) ?m)        :ordered (((?m . 9))))
  ((cl-prolog::min_list (3 9 2) ?m)        :ordered (((?m . 2))))
  ((cl-prolog::max_list () ?m)             :fails)
  ((cl-prolog::numlist 1 5 ?l)             :ordered (((?l . (1 2 3 4 5)))))
  ((cl-prolog::numlist 3 3 ?l)             :ordered (((?l . (3)))))
  ((cl-prolog::numlist 5 1 ?l)             :fails)
  ((cl-prolog::numlist ?x 5 ?l)            :signals)
  ((cl-prolog::sum_list (1 2 a) ?s)        :signals)
  ((cl-prolog::sum_list ?unbound ?s)       :signals)
  ((cl-prolog::max_list (1 a) ?m)          :signals)
  ((cl-prolog::min_list () ?m)             :fails)
  ((cl-prolog::numlist 1 ?hi ?l)           :signals)
  ((cl-prolog::numlist 1.5 5 ?l)           :signals)
  ((cl-prolog::list_to_set (a b a c b) ?s) :ordered (((?s . (a b c)))))
  ((cl-prolog::list_to_set (3 1 3 2 1) ?s) :ordered (((?s . (3 1 2)))))
  ((cl-prolog::list_to_set () ?s)          :ordered (((?s . ()))))
  ((cl-prolog::subtract (a b c d) (b d) ?r) :ordered (((?r . (a c)))))
  ((cl-prolog::subtract (a b c) (a b c) ?r) :ordered (((?r . ()))))
  ((cl-prolog::subtract improper (b) ?r)   :signals)
  ((cl-prolog::intersection (a b c) (b c d) ?r) :ordered (((?r . (b c)))))
  ((cl-prolog::union (a b) (b c d) ?r)     :ordered (((?r . (a b c d)))))
  ((cl-prolog::union (a b b) (b c) ?r)     :ordered (((?r . (a b c)))))
  ((cl-prolog::permutation (1 2 3) ?p)
   :set (((?p . (1 2 3))) ((?p . (1 3 2))) ((?p . (2 1 3)))
         ((?p . (2 3 1))) ((?p . (3 1 2))) ((?p . (3 2 1)))))
  ((cl-prolog::permutation (a b) (b a))    :succeeds)
  ((cl-prolog::permutation ?x (1 2))       :set (((?x . (1 2))) ((?x . (2 1)))))
  ((cl-prolog::permutation ?x ?y)          :signals))

(deftest numlist-obeys-builtin-output-length-limit ()
  (let ((cl-prolog:*max-prolog-builtin-output-length* 1))
    (signals-condition prolog-resource-error
      (query-prolog (make-rulebase)
                    (quote (cl-prolog::numlist 1 2 ?list)))))
  (let ((cl-prolog:*max-prolog-builtin-output-length* nil))
    (is-equal (quote (((?list . (1 2)))))
              (query-prolog (make-rulebase)
                            (quote (cl-prolog::numlist 1 2 ?list))))))

(defun make-apply-rulebase ()
  (prolog
    ((double ?x ?y) (is ?y (* 2 ?x)))
    ((add ?e ?a ?b) (is ?b (+ ?a ?e)))
    ((add2 ?e1 ?e2 ?a ?b) (is ?b (+ (+ ?a ?e1) ?e2)))
    ((add3 ?e1 ?e2 ?e3 ?a ?b) (is ?b (+ (+ (+ ?a ?e1) ?e2) ?e3)))
    ((triple ?x ?y ?z) (is ?z (+ (+ ?x ?x) ?x)) (= ?y ?z))
    ((even ?x) (is ?r (mod ?x 2)) (= ?r 0))
    ((positive ?x) (> ?x 0))))

(deftest-queries apply-meta-builtins ((make-apply-rulebase))
  ;; maplist across arities 2..5
  ((cl-prolog::maplist positive (1 2 3))    :succeeds)
  ((cl-prolog::maplist positive (1 -2 3))   :fails)
  ((cl-prolog::maplist double (1 2 3) ?ys)  :ordered (((?ys . (2 4 6)))))
  ((cl-prolog::maplist double () ?ys)       :ordered (((?ys . ()))))
  ((cl-prolog::maplist double (1 2 3) (2 4 7)) :fails)
  ((cl-prolog::maplist add (1 2 3) (10 20 30) ?zs) :ordered (((?zs . (11 22 33)))))
  ((cl-prolog::maplist add2 (1 2) (10 20) (100 200) ?zs)
   :ordered (((?zs . (111 222)))))
  ;; maplist generative mode: output list unbound, driven by second proper list
  ((cl-prolog::maplist = ?xs (a b c)) :ordered (((?xs . (a b c)))))
  ;; foldl across arities 4..6
  ((cl-prolog::foldl add (1 2 3 4) 0 ?sum)  :ordered (((?sum . 10))))
  ((cl-prolog::foldl add () 42 ?sum)        :ordered (((?sum . 42))))
  ((cl-prolog::foldl add2 (1 2 3) (4 5 6) 0 ?sum) :ordered (((?sum . 21))))
  ((cl-prolog::foldl add3 (1 2) (10 20) (100 200) 0 ?sum)
   :ordered (((?sum . 333))))
  ((cl-prolog::foldl add2 (1 2) (3) 0 ?sum) :fails)
  ((cl-prolog::foldl ?g (1) 0 ?sum)         :signals)
  ;; include / exclude / partition
  ((cl-prolog::include even (1 2 3 4 5 6) ?e) :ordered (((?e . (2 4 6)))))
  ((cl-prolog::exclude even (1 2 3 4 5 6) ?e) :ordered (((?e . (1 3 5)))))
  ((cl-prolog::partition even (1 2 3 4) ?in ?out)
   :ordered (((?in . (2 4)) (?out . (1 3)))))
  ((cl-prolog::include positive (-1 2 -3 4) ?e) :ordered (((?e . (2 4)))))
  ((cl-prolog::include even () ?e)          :ordered (((?e . ()))))
  ((cl-prolog::include ?g (1) ?e)           :signals)
  ((cl-prolog::include even improper ?e)    :signals)
  ((cl-prolog::maplist ?unbound (1) ?ys)    :signals))
